version: '3'

services:
  dashboard-boilerplate-antd:
    container_name: dashboard-boilerplate-antd
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
