version: '3'

services:
  dashboard-boilerplate:
    container_name: dashboard-boilerplate
    image: node:10-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn && yarn start"
    ports:
      - 3000:3000
      - 9229:9229 # vscode debugger
